project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Alert** - this is some information that you should pay attention to"
  #   type: primary
  #   position: below-navbar
  title: "GIS Portfolio"
  site-url: https://cdbyl.github.io/portfolio
  description: "Carolina Byl's Portfolio"
  favicon: loguito.png
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@cdbyl"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: projects.html
      #- text: "Blog"
      #  href: blog.html
      #- icon: rss
      #  href: blog.xml
  page-footer:
    left: "Site created with Quarto"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [lux, light.scss]
      dark: [lux, dark.scss]
    toc: true


